(function () {
    const pages = {
        schulprofil: {
            eyebrow: '🏫 Unsere Schule', title: 'Ein Ort zum Lernen, Lachen und Wachsen', intro: 'Die VS Puch bei Weiz ist eine kleine, herzliche Schule mit viel Raum für Neugier, Bewegung und gemeinsames Entdecken.',
            content: `<div class="grid lg:grid-cols-3 gap-6"><div class="lg:col-span-2 bg-white rounded-3xl p-8 shadow-sm prose-school"><h2>Unsere Schule</h2><p>Bei uns kennt man sich. Kinder, Familien und Pädagoginnen arbeiten gemeinsam daran, dass Lernen Freude macht und jedes Kind seinen eigenen Weg gehen kann.</p><p>Wir verbinden verlässliche Grundlagen mit kreativen Projekten, Bewegung und einem achtsamen Miteinander. Dabei darf jedes Kind Fragen stellen, ausprobieren und an seinen Aufgaben wachsen.</p><h2>Was uns wichtig ist</h2><div class="grid sm:grid-cols-2 gap-4 not-prose"><div class="bg-primary/10 rounded-2xl p-5"><span class="text-3xl">💛</span><h3 class="font-display font-bold text-lg mt-2">Miteinander</h3><p class="text-sm text-tertiary mt-1">Wir helfen einander und feiern gemeinsame Erfolge.</p></div><div class="bg-secondary/10 rounded-2xl p-5"><span class="text-3xl">🔍</span><h3 class="font-display font-bold text-lg mt-2">Neugier</h3><p class="text-sm text-tertiary mt-1">Wir entdecken die Welt mit offenen Augen.</p></div><div class="bg-secondary-container/60 rounded-2xl p-5"><span class="text-3xl">🌱</span><h3 class="font-display font-bold text-lg mt-2">Verantwortung</h3><p class="text-sm text-tertiary mt-1">Wir achten aufeinander und auf unsere Umwelt.</p></div><div class="bg-tertiary/10 rounded-2xl p-5"><span class="text-3xl">🎨</span><h3 class="font-display font-bold text-lg mt-2">Kreativität</h3><p class="text-sm text-tertiary mt-1">Wir geben Ideen Platz und machen sie sichtbar.</p></div></div></div><div class="bg-secondary text-white rounded-3xl p-8 flex flex-col justify-between"><div><span class="text-5xl">🌈</span><h2 class="font-display font-bold text-3xl mt-5">Gemeinsam stark</h2><p class="text-white/80 mt-4 leading-relaxed">Eine Schule ist mehr als ein Gebäude. Sie ist eine Gemeinschaft, in der Kinder sicher, gesehen und ermutigt aufwachsen.</p></div><a href="team.html" class="mt-8 inline-flex justify-center px-5 py-3 bg-white text-secondary rounded-2xl font-display font-bold">Unser Team kennenlernen →</a></div></div>`
        },
        klassen: {
            eyebrow: '📚 Unsere Klassen', title: 'Jede Klasse ist eine kleine Gemeinschaft', intro: 'In unseren Klassen wird gemeinsam gelernt, gespielt, geforscht und gefeiert.',
            content: `<div class="grid md:grid-cols-2 gap-6">${classCard('1a', 'Die Entdecker', 'Hier beginnt die große Reise durch die Schule. Wir lernen mit allen Sinnen und probieren jeden Tag etwas Neues aus.', '🧭', 'primary')}${classCard('2a', 'Die Naturforscher', 'Wir beobachten, fragen nach und finden spannende Antworten in Büchern, im Garten und draußen in der Natur.', '🌿', 'secondary')}${classCard('3a', 'Die Kreativköpfe', 'Ob Musik, Kunst, Theater oder Geschichten: Unsere Ideen dürfen bunt, laut und ganz besonders sein.', '🎨', 'secondary')}${classCard('4a', 'Die großen Begleiter', 'Wir übernehmen Verantwortung, helfen den Jüngeren und sind bereit für den nächsten Schritt.', '🚀', 'tertiary')}</div><div class="mt-10 bg-white rounded-3xl p-8 text-center shadow-sm"><span class="text-4xl">🤝</span><h2 class="font-display font-bold text-2xl mt-3">Gemeinsam lernen</h2><p class="text-tertiary max-w-2xl mx-auto mt-2">Klassenübergreifende Projekte verbinden unsere Kinder und machen aus vielen einzelnen Gruppen eine starke Schulgemeinschaft.</p></div>`
        },
        aktuelles: {
            eyebrow: '📰 Neuigkeiten', title: 'Was gibt es Neues?', intro: 'Hier findest du Geschichten, Rückblicke und wichtige Informationen aus unserem Schulalltag.',
            content: `<div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">${newsCard('🎓', 'Abschlussfeier der 4. Klasse', 'Ein bewegender Tag voller Erinnerungen, Musik und guter Wünsche für unsere großen Kinder.', '15. März 2026', 'primary', 'https://images.unsplash.com/photo-1588072432836-e10032774350?w=700&h=440&fit=crop')}${newsCard('🌍', 'Projektwoche Unsere Erde', 'Eine Woche lang wurde geforscht, gebaut, gepflanzt und über unsere Umwelt gelernt.', '8. März 2026', 'secondary', 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=700&h=440&fit=crop')}${newsCard('🎭', 'Fasching an der VS Puch', 'Bunte Kostüme, lustige Spiele und ganz viel Lachen im ganzen Schulhaus.', '1. März 2026', 'primary', 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=700&h=440&fit=crop')}${newsCard('🏃', 'Sporttag im Frühling', 'Teamgeist, Bewegung und viele persönliche Bestleistungen auf unserem Sportplatz.', '20. Februar 2026', 'secondary', 'https://images.unsplash.com/photo-1529390079861-591de354faf5?w=700&h=440&fit=crop')}${newsCard('📖', 'Vorlesetag', 'Mit Geschichten im Gepäck haben wir gemeinsam neue Welten entdeckt.', '10. Februar 2026', 'tertiary', 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=700&h=440&fit=crop')}${newsCard('🌱', 'Start im Schulgarten', 'Die ersten Samen sind gesetzt. Jetzt heißt es pflegen, beobachten und geduldig sein.', '28. Jänner 2026', 'secondary', 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=700&h=440&fit=crop')}</div>`
        },
        blogpost: {
            eyebrow: '🎓 Schulleben', title: 'Abschlussfeier der 4. Klasse', intro: 'Ein Tag voller Lieder, Erinnerungen und großer Vorfreude auf alles, was kommt.',
            content: `<article class="max-w-4xl mx-auto bg-white rounded-3xl overflow-hidden shadow-sm"><img src="https://images.unsplash.com/photo-1588072432836-e10032774350?w=1200&h=560&fit=crop" alt="Kinder bei einer Schulfeier" class="w-full h-64 md:h-96 object-cover"><div class="p-8 md:p-12 prose-school"><div class="flex flex-wrap gap-2"><span class="px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-bold">Schulleben</span><time class="px-3 py-1 rounded-full bg-surface-alt text-tertiary text-sm">15. März 2026</time></div><h2>Ein Abschied mit ganz viel Herz</h2><p>Wenn vier Jahre Volksschule zu Ende gehen, ist das ein besonderer Moment. Unsere Viertklässlerinnen und Viertklässler haben mit ihren Klassen ein buntes Programm vorbereitet.</p><p>Es wurde gesungen, gelacht und auf gemeinsame Erlebnisse zurückgeblickt. Besonders schön war, dass auch die jüngeren Kinder mit kleinen Beiträgen dabei waren.</p><blockquote class="my-8 rounded-2xl bg-secondary text-white p-6 font-display text-2xl font-bold">„Wir nehmen viele schöne Erinnerungen mit – und sind bereit für neue Abenteuer!“</blockquote><p>Wir wünschen unseren großen Kindern alles Gute für ihren weiteren Weg und freuen uns, wenn sie uns wieder besuchen kommen.</p><a href="aktuelles.html" class="inline-flex mt-6 px-6 py-3 bg-primary text-white rounded-2xl font-display font-bold">← Zurück zu den Neuigkeiten</a></div></article>`
        },
        team: {
            eyebrow: '👩‍🏫👨‍🏫 Unser Team', title: 'Menschen, die Kinder stark machen', intro: 'Unser Team begleitet Kinder mit Fachwissen, Geduld, Humor und ganz viel Herz.',
            content: `<div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">${personCard('Lisa Müller', 'Direktorin', '👑', '1573496359142-b8d87734a5a2')}${personCard('Stefanie Huber', 'Klassenlehrerin 1a', '📚', '1580489944761-15a19d654956')}${personCard('Thomas Berger', 'Klassenlehrer 2a', '🌿', '1594744803329-e58b31de8bf5')}${personCard('Andrea Winkler', 'Sonderpädagogin', '🧠', '1515378960530-7c0da6231fb1')}${personCard('Petra Steiner', 'Hortbetreuung', '🎨', '1488426862026-3ee34a7d66df')}${personCard('Klaus Eder', 'Musik & Bewegung', '🎵', '1544717305-2782549b5136')}</div>`
        },
        projekte: {
            eyebrow: '🌱 Projekte', title: 'Lernen wird zum Abenteuer', intro: 'Unsere Projekte verbinden Fächer, Klassen und die Welt außerhalb des Klassenzimmers.',
            content: `<div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">${projectCard('🌳', 'Waldtage', 'Wir entdecken den Wald zu jeder Jahreszeit und lernen Pflanzen, Tiere und Zusammenhänge kennen.', 'Alle Klassen')}${projectCard('🌻', 'Unser Schulgarten', 'Vom Samen bis zur Ernte: Im Garten erleben Kinder, wie aus Pflege etwas wachsen kann.', '1a · 2a · 3a')}${projectCard('📖', 'Magische Lesenacht', 'Mit Taschenlampen, Geschichten und Kuscheldecken wird Lesen zu einem ganz besonderen Erlebnis.', '3a · 4a')}${projectCard('🎨', 'Farben der Natur', 'Wir stellen Farben selbst her und gestalten Bilder mit Materialien aus unserer Umgebung.', '1a · 1b')}${projectCard('🎵', 'Singen verbindet', 'Gemeinsames Singen, Musizieren und Auftreten stärkt unsere Stimmen und unser Miteinander.', 'Alle Klassen')}${projectCard('♻️', 'Klimaschule', 'Wir sammeln Ideen für einen achtsamen Umgang mit Energie, Wasser und unserer Umwelt.', 'Schulprojekt') }</div>`
        },
        termine: {
            eyebrow: '📅 Kalender', title: 'Termine, Ferien & Feste', intro: 'Damit Familien gut planen können: die wichtigsten Termine des Schuljahres auf einen Blick.',
            content: `<div class="grid lg:grid-cols-3 gap-6 mb-8"><div class="lg:col-span-2 bg-white rounded-3xl p-8 shadow-sm"><h2 class="font-display font-bold text-2xl mb-5">Die nächsten Termine</h2><div class="space-y-3">${eventRow('15', 'Mai', 'Sporttag der VS Puch', '8:00–14:00 Uhr · Sportplatz Puch', '🏃')}${eventRow('20', 'Mai', 'Elternabend 3. Klassen', '19:00 Uhr · Aula', '👪')}${eventRow('06', 'Jun', 'Schulausflug ins Almenland', 'Ganztägig · Klasse 1a & 1b', '🚌')}${eventRow('13', 'Jun', 'Tag der offenen Tür', '9:00–12:00 Uhr · Alle willkommen', '🏫')}${eventRow('27', 'Jun', 'Schulschlussfeier', '10:00 Uhr · Schulhof', '🎉')}</div></div><div class="bg-secondary text-white rounded-3xl p-8"><span class="text-5xl">🌞</span><h2 class="font-display font-bold text-2xl mt-5">Sommerferien</h2><p class="text-white/80 mt-3">5. Juli bis 7. September 2025</p><p class="text-white/70 text-sm mt-6">Weitere Ferientermine und aktuelle Änderungen erhalten Sie im Sekretariat.</p></div></div><div class="bg-primary/10 rounded-3xl p-8"><h2 class="font-display font-bold text-2xl">Ferienkalender 2025/26</h2><div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-5"><div class="bg-white rounded-2xl p-4"><b>Herbstferien</b><p class="text-sm text-tertiary mt-1">27.–31. Oktober</p></div><div class="bg-white rounded-2xl p-4"><b>Weihnachtsferien</b><p class="text-sm text-tertiary mt-1">24. Dezember–6. Jänner</p></div><div class="bg-white rounded-2xl p-4"><b>Semesterferien</b><p class="text-sm text-tertiary mt-1">16.–21. Februar</p></div><div class="bg-white rounded-2xl p-4"><b>Osterferien</b><p class="text-sm text-tertiary mt-1">28. März–6. April</p></div></div></div>`
        },
        kontakt: {
            eyebrow: '📬 Kontakt', title: 'Wir sind gerne für Sie da', intro: 'Frage, Anliegen oder Idee? Schreiben Sie uns oder besuchen Sie uns in Puch bei Weiz.',
            content: `<div class="grid lg:grid-cols-2 gap-6"><div class="space-y-6"><div class="bg-secondary text-white rounded-3xl p-8"><h2 class="font-display font-bold text-3xl mb-7">Sekretariat</h2>${contactRow('📍', 'Adresse', 'Puch 104 · 8182 Puch bei Weiz')}${contactRow('📞', 'Telefon', '+43 3177 2228')}${contactRow('✉️', 'E-Mail', 'direktion@vs-puch.at')}</div><div class="bg-white rounded-3xl p-8 shadow-sm"><h2 class="font-display font-bold text-2xl mb-5">Öffnungszeiten 🕐</h2><div class="space-y-3 text-sm"><div class="flex justify-between"><b>Montag–Donnerstag</b><span class="text-tertiary">7:30–12:00</span></div><div class="flex justify-between"><b>Freitag</b><span class="text-tertiary">7:30–11:00</span></div><div class="flex justify-between text-tertiary"><b>Samstag & Sonntag</b><span>geschlossen</span></div></div></div></div><div class="bg-white rounded-3xl p-8 shadow-sm"><h2 class="font-display font-bold text-2xl mb-2">Nachricht senden ✉️</h2><p class="text-tertiary text-sm mb-7">Wir antworten in der Regel innerhalb eines Schultages.</p><form class="space-y-4" data-demo-form><div class="grid sm:grid-cols-2 gap-4"><input required class="w-full px-4 py-3 bg-surface-alt rounded-2xl border-0 focus:ring-2 focus:ring-primary/30" placeholder="Vorname"><input required class="w-full px-4 py-3 bg-surface-alt rounded-2xl border-0 focus:ring-2 focus:ring-primary/30" placeholder="Nachname"></div><input required type="email" class="w-full px-4 py-3 bg-surface-alt rounded-2xl border-0 focus:ring-2 focus:ring-primary/30" placeholder="E-Mail-Adresse"><textarea required rows="5" class="w-full px-4 py-3 bg-surface-alt rounded-2xl border-0 focus:ring-2 focus:ring-primary/30 resize-none" placeholder="Ihre Nachricht"></textarea><button class="w-full px-6 py-4 bg-primary text-white rounded-2xl font-display font-bold">Nachricht senden 🚀</button><p class="hidden text-secondary font-bold" data-form-success>Danke! Ihre Nachricht wurde als Prototyp angenommen.</p></form></div></div>`
        },
        downloads: {
            eyebrow: '📄 Service', title: 'Downloads für Familien', intro: 'Wichtige Formulare und Informationen bequem zum Nachlesen und Herunterladen.',
            content: `<div class="grid md:grid-cols-2 gap-6">${downloadCard('📅', 'Schulkalender 2025/26', 'Alle Ferien, Feiertage und wichtigen Schultermine.', 'PDF · 240 KB')}${downloadCard('📝', 'Anmeldeformular', 'Formular für die Schuleinschreibung und wichtige Hinweise.', 'PDF · 180 KB')}${downloadCard('🎒', 'Materialliste 1. Klasse', 'Alles, was Ihr Kind für den Schulstart braucht.', 'PDF · 120 KB')}${downloadCard('🤝', 'Leitfaden für Eltern', 'Ansprechpersonen, Regeln und Tipps für den Schulalltag.', 'PDF · 310 KB')}${downloadCard('🍎', 'Mittagsbetreuung', 'Informationen zur Anmeldung und zu den Betreuungszeiten.', 'PDF · 150 KB')}${downloadCard('🌿', 'Unsere Projekte', 'Ein Überblick über Projekte und Schwerpunkte der Schule.', 'PDF · 420 KB')}</div>`
        },
        anfahrt: {
            eyebrow: '🗺️ Anfahrt', title: 'So finden Sie zu uns', intro: 'Die Volksschule Puch liegt mitten in der Gemeinde und ist gut zu Fuß, mit dem Fahrrad und mit dem Auto erreichbar.',
            content: `<div class="grid lg:grid-cols-2 gap-6"><div class="bg-secondary text-white rounded-3xl p-8"><span class="text-6xl">📍</span><h2 class="font-display font-bold text-3xl mt-6">Volksschule Puch</h2><p class="text-white/80 text-lg mt-2">Puch 104<br>8182 Puch bei Weiz<br>Steiermark, Österreich</p><div class="mt-8 space-y-3 text-white/80"><p>🚶 Zu Fuß: zentral im Ortsgebiet</p><p>🚲 Fahrrad: Fahrradständer beim Eingang</p><p>🚗 Auto: Parkplätze in der Nähe</p><p>🚌 Bus: Haltestelle Gemeindeamt</p></div></div><div class="bg-primary/10 rounded-3xl min-h-80 flex items-center justify-center p-8 text-center"><div><span class="text-7xl">🗺️</span><h2 class="font-display font-bold text-2xl mt-4">Karte folgt</h2><p class="text-tertiary mt-2">Hier kann später eine interaktive Karte eingebunden werden.</p><a href="kontakt.html" class="inline-flex mt-6 px-6 py-3 bg-primary text-white rounded-2xl font-display font-bold">Kontakt aufnehmen</a></div></div></div>`
        },
        impressum: { eyebrow: '📄 Rechtliches', title: 'Impressum', intro: 'Angaben zum Betreiber dieser Website.', content: legalContent('Volksschule Puch bei Weiz', 'Puch 104<br>8182 Puch bei Weiz<br>Österreich', 'direktion@vs-puch.at', 'Diese Website ist ein nicht-kommerzieller Prototyp. Inhalte und Kontaktdaten dienen der Darstellung und müssen vor einer Veröffentlichung rechtlich geprüft und aktualisiert werden.') },
        datenschutz: { eyebrow: '🔒 Rechtliches', title: 'Datenschutzerklärung', intro: 'Informationen zum Umgang mit personenbezogenen Daten.', content: legalContent('Datenschutz im Prototyp', '', '', 'Diese Prototyp-Seite verarbeitet keine Nachrichten serverseitig und verwendet keine Analyse- oder Tracking-Dienste. Externe Bilder und Schriftarten werden von Drittanbietern geladen. Für einen produktiven Einsatz müssen Hosting, Kontaktformular, Cookies und eingebundene Dienste rechtlich geprüft und in einer vollständigen Datenschutzerklärung dokumentiert werden.') }
    };

    function classCard(name, title, text, icon, color) { return `<article class="page-card bg-white rounded-3xl p-7 shadow-sm border-t-8 border-${color}"><span class="text-5xl">${icon}</span><h2 class="font-display font-bold text-2xl mt-5">Klasse ${name}</h2><p class="text-primary font-bold mt-1">${title}</p><p class="text-tertiary leading-relaxed mt-4">${text}</p><a href="kontakt.html" class="inline-flex mt-5 text-secondary font-bold">Kontakt zur Klasse →</a></article>`; }
    function newsCard(icon, title, text, date, color, image) { return `<article class="page-card bg-white rounded-3xl overflow-hidden shadow-sm"><div class="relative h-52 overflow-hidden"><img src="${image}" alt="${title}" class="w-full h-full object-cover transition-transform duration-500 hover:scale-105"><span class="absolute top-4 left-4 w-12 h-12 rounded-2xl bg-white/90 flex items-center justify-center text-2xl shadow-sm">${icon}</span></div><div class="p-7"><p class="text-xs text-tertiary">${date}</p><h2 class="font-display font-bold text-xl mt-2">${title}</h2><p class="text-tertiary leading-relaxed mt-3">${text}</p><a href="blogpost.html" class="inline-flex mt-5 text-primary font-bold">Weiterlesen →</a></div></article>`; }
    function personCard(name, role, icon, image) { return `<article class="page-card bg-white rounded-3xl p-7 shadow-sm text-center"><div class="relative w-32 h-32 mx-auto"><img src="https://images.unsplash.com/photo-${image}?w=240&h=240&fit=crop" alt="${name}" class="w-full h-full object-cover rounded-full ring-4 ring-secondary-container"><span class="absolute -bottom-1 -right-1 w-10 h-10 bg-primary rounded-full flex items-center justify-center text-xl">${icon}</span></div><h2 class="font-display font-bold text-xl mt-6">${name}</h2><p class="text-tertiary mt-1">${role}</p><a href="kontakt.html" class="inline-flex mt-4 text-secondary font-bold text-sm">Kontakt aufnehmen →</a></article>`; }
    function projectCard(icon, title, text, group) { return `<article class="page-card bg-white rounded-3xl p-7 shadow-sm"><span class="text-5xl">${icon}</span><span class="block text-xs text-secondary font-bold uppercase tracking-wide mt-5">${group}</span><h2 class="font-display font-bold text-2xl mt-2">${title}</h2><p class="text-tertiary leading-relaxed mt-3">${text}</p><a href="kontakt.html" class="inline-flex mt-5 text-primary font-bold">Mehr erfahren →</a></article>`; }
    function eventRow(day, month, title, detail, icon) { return `<div class="flex items-center gap-4 p-4 rounded-2xl hover:bg-surface-alt"><div class="w-16 h-16 shrink-0 bg-primary text-white rounded-2xl flex flex-col items-center justify-center"><b class="font-display text-2xl leading-none">${day}</b><span class="text-xs">${month}</span></div><div class="flex-1"><b class="font-display text-lg">${title}</b><p class="text-sm text-tertiary mt-1">${detail}</p></div><span class="text-2xl hidden sm:block">${icon}</span></div>`; }
    function contactRow(icon, label, text) { return `<div class="flex items-start gap-4 mb-6"><span class="w-12 h-12 bg-white/15 rounded-2xl flex items-center justify-center text-2xl shrink-0">${icon}</span><div><b class="font-display text-lg">${label}</b><p class="text-white/75 mt-1">${text}</p></div></div>`; }
    function downloadCard(icon, title, text, meta) { return `<a href="kontakt.html" class="page-card bg-white rounded-3xl p-7 shadow-sm flex items-start gap-5"><span class="text-4xl">${icon}</span><span><b class="font-display text-xl">${title}</b><span class="block text-tertiary mt-2">${text}</span><span class="inline-block mt-4 px-3 py-1 bg-secondary/10 text-secondary text-xs font-bold rounded-full">${meta} · Auf Anfrage</span></span></a>`; }
    function legalContent(heading, address, email, text) { return `<div class="max-w-3xl bg-white rounded-3xl p-8 md:p-12 shadow-sm prose-school"><h2>${heading}</h2>${address ? `<p>${address}</p>` : ''}${email ? `<p>E-Mail: ${email}</p>` : ''}<p>${text}</p><h2>Hinweis</h2><p>Diese Seite ist Teil eines HTML-Prototypen für die Volksschule Puch bei Weiz.</p></div>`; }

    function header() { return `<header class="fixed top-0 left-0 right-0 z-50 bg-surface/95 backdrop-blur-md border-b-2 border-primary/10 shadow-sm"><div class="max-w-7xl mx-auto px-6 lg:px-10 h-20 flex items-center justify-between"><a href="index.html" class="flex items-center gap-3"><div class="w-12 h-12 bg-gradient-to-br from-primary to-primary-dark rounded-2xl flex items-center justify-center shadow-md"><img src="logo.svg" alt="Logo VS Puch" class="h-8 w-auto brightness-0 invert"></div><div class="hidden sm:block"><p class="font-display font-bold text-xl text-primary">VS Puch</p><p class="text-xs text-tertiary/70 -mt-0.5">bei Weiz</p></div></a><nav class="hidden md:flex items-center gap-1"><a href="index.html" class="nav-link">🏠 Startseite</a><a href="schulprofil.html" class="nav-link">🏫 Schule</a><a href="klassen.html" class="nav-link">📚 Klassen</a><a href="news.html" class="nav-link">📰 Aktuelles</a><a href="team.html" class="nav-link">👩‍🏫 Team</a><a href="kontakt.html" class="ml-3 px-5 py-3 bg-primary text-white rounded-2xl font-bold">📞 Kontakt</a></nav><button class="md:hidden p-3 rounded-xl hover:bg-surface-alt" data-menu-button aria-label="Menü öffnen">☰</button></div><nav class="hidden md:hidden bg-surface px-6 pb-5 shadow-lg" data-mobile-menu><a href="index.html" class="mobile-link">🏠 Startseite</a><a href="schulprofil.html" class="mobile-link">🏫 Schule</a><a href="klassen.html" class="mobile-link">📚 Klassen</a><a href="news.html" class="mobile-link">📰 Aktuelles</a><a href="team.html" class="mobile-link">👩‍🏫 Team</a><a href="kontakt.html" class="mobile-link">📞 Kontakt</a></nav></header>`; }
    function footer() { return `<footer class="bg-on-surface text-white mt-20"><div class="max-w-7xl mx-auto px-6 lg:px-10 py-14"><div class="flex flex-col md:flex-row justify-between gap-8"><div><p class="font-display font-bold text-xl">VS Puch bei Weiz</p><p class="text-white/50 mt-2">Volksschule mit Herz und Seele ❤️</p></div><div class="grid grid-cols-2 sm:grid-cols-3 gap-x-8 gap-y-3 text-sm text-white/65"><a href="termine.html">📅 Termine</a><a href="projekte.html">🌱 Projekte</a><a href="downloads.html">📄 Downloads</a><a href="anfahrt.html">🗺️ Anfahrt</a><a href="impressum.html">Impressum</a><a href="datenschutz.html">Datenschutz</a></div></div><div class="border-t border-white/10 mt-10 pt-6 text-sm text-white/40 flex flex-col sm:flex-row justify-between gap-2"><span>© 2026 Volksschule Puch bei Weiz</span><span>Mit Liebe zum Lernen 🍎</span></div></div></footer>`; }

    const current = document.querySelector('[data-page]');
    if (!current) return;
    const page = pages[current.dataset.page] || pages.schulprofil;
    document.getElementById('site-header').innerHTML = header();
    document.getElementById('page-content').innerHTML = `<section class="page-hero pt-32 pb-16"><div class="max-w-7xl mx-auto px-6 lg:px-10"><span class="inline-flex px-5 py-2 bg-secondary-container text-secondary rounded-full font-display font-bold">${page.eyebrow}</span><h1 class="font-display font-black text-5xl md:text-7xl leading-tight mt-6 max-w-4xl">${page.title}</h1><p class="text-lg md:text-xl text-tertiary max-w-2xl mt-6 leading-relaxed">${page.intro}</p></div></section><section class="py-16 md:py-24 bg-surface-alt"><div class="max-w-7xl mx-auto px-6 lg:px-10">${page.content}</div></section>`;
    document.getElementById('site-footer').innerHTML = footer();
    document.querySelector('[data-menu-button]').addEventListener('click', function () { document.querySelector('[data-mobile-menu]').classList.toggle('hidden'); });
    document.querySelectorAll('[data-demo-form]').forEach(function (form) { form.addEventListener('submit', function (event) { event.preventDefault(); form.querySelector('[data-form-success]').classList.remove('hidden'); }); });
})();
